#!/usr/bin/env python3
"""Preview or export a complete, bounded GitHub Pages snapshot without changing originals.

Run with --apply to copy the selected site into qa-output/pages. The default
only reports the selection. Start a new export directory for every snapshot.
"""
from __future__ import annotations

import argparse
from collections import Counter
from datetime import datetime, timezone
import hashlib
from html.parser import HTMLParser
import json
from pathlib import Path, PurePosixPath
import shutil
import subprocess
from urllib.parse import unquote, urlsplit

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_BUDGET = 999_000_000
DEFAULT_RESERVE = 2_000_000
MAX_FILE_BYTES = 100 * 1024 * 1024
GENERATED = {'media/library.json', 'media/library.js', 'media/pages-selection.json', '.nojekyll'}


def source_path(root, relative):
    """Require a regular repository file, without traversal or symbolic links."""
    if not isinstance(relative, str) or not relative or '\\' in relative:
        raise ValueError(f'Invalid relative path: {relative!r}')
    parts = PurePosixPath(relative).parts
    if not parts or PurePosixPath(relative).is_absolute() or '..' in parts or ':' in relative:
        raise ValueError(f'Unsafe relative path: {relative!r}')
    if any(part.lower() == '.git' for part in parts):
        raise ValueError('Git internals cannot be published')
    root = Path(root).resolve()
    path = root.joinpath(*parts)
    current = root
    for part in parts:
        current = current / part
        if current.is_symlink():
            raise ValueError(f'Symbolic links cannot be published: {relative}')
    if not path.resolve().is_relative_to(root):
        raise ValueError(f'Path outside repository: {relative}')
    if not path.is_file():
        raise FileNotFoundError(f'Missing source file: {relative}')
    return path


class PageAssets(HTMLParser):
    def __init__(self):
        super().__init__()
        self.paths = set()

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        value = attrs.get('src') if tag in {'img', 'script', 'video', 'source'} else None
        if tag == 'link' and attrs.get('rel') in {'stylesheet', 'icon', 'preload'}:
            value = attrs.get('href')
        if value:
            url = urlsplit(value)
            if not url.scheme and not url.netloc and url.path:
                self.paths.add(unquote(url.path))


def base_files(root):
    required = {'index.html', 'style.css', 'script.js', '.gitignore', 'README.md',
                'media/ADDING-MEMORIES.md', 'media/preview-unavailable.svg'}
    required.update(path.relative_to(root).as_posix() for path in root.glob('*.svg'))
    required.update(path.relative_to(root).as_posix() for path in (root / 'scripts').glob('*.py'))
    parser = PageAssets()
    parser.feed(source_path(root, 'index.html').read_text(encoding='utf-8'))
    required.update(parser.paths - GENERATED)
    return {relative: source_path(root, relative).stat().st_size for relative in sorted(required)}


def counts(items):
    result = Counter(item['type'] for item in items)
    return {'memories': len(items), 'photos': result['image'], 'videos': result['video']}


def json_bytes(value):
    return (json.dumps(value, ensure_ascii=False, indent=2) + '\n').encode('utf-8')


def generated_files(plan):
    """Account for the report's own byte count, including its total-size field."""
    library = plan['library']
    result = {'media/library.json': json_bytes(library),
              'media/library.js': ('/* Generated by scripts/prepare_pages.py. */\nwindow.MEDIA_LIBRARY = ' +
                                   json.dumps(library, ensure_ascii=False, separators=(',', ':')) + ';\n').encode('utf-8'),
              '.nojekyll': b''}
    report = plan['report']
    report['generatedFiles'] = [{'path': path, 'bytes': len(data)} for path, data in sorted(result.items())]
    report['generatedFiles'].append({'path': 'media/pages-selection.json', 'bytes': 0})
    report['totalBytes'] = 0
    for _ in range(20):
        report_data = json_bytes(report)
        total = sum(plan['files'].values()) + sum(map(len, result.values())) + len(report_data)
        if report['totalBytes'] == total and report['generatedFiles'][-1]['bytes'] == len(report_data):
            result['media/pages-selection.json'] = report_data
            return result
        report['totalBytes'] = total
        report['generatedFiles'][-1]['bytes'] = len(report_data)
    raise RuntimeError('Could not account for generated report size')


def make_plan(root=ROOT, budget=DEFAULT_BUDGET, reserve=DEFAULT_RESERVE):
    root = Path(root).resolve()
    if reserve < 0 or budget <= reserve:
        raise ValueError('Budget must be larger than the nonnegative metadata reserve')
    if budget > 1_000_000_000:
        raise ValueError('Budget cannot exceed the GitHub Pages 1 GB site limit')
    library = json.loads(source_path(root, 'media/library.json').read_text(encoding='utf-8'))
    items = library.get('items')
    if not isinstance(items, list):
        raise ValueError('Catalog must contain an items list')
    files = base_files(root)
    if any(size > MAX_FILE_BYTES for size in files.values()):
        raise ValueError('A site support file exceeds GitHub\'s 100 MiB file limit')
    if sum(files.values()) > budget - reserve:
        raise ValueError('Site support files exceed the available budget')
    candidates, excluded = [], []
    for index, item in enumerate(items):
        if item.get('type') not in {'image', 'video'} or not item.get('src'):
            raise ValueError(f'Invalid catalog item at index {index}')
        dependencies = {item[key] for key in ('src', 'thumbnail', 'playbackSrc') if item.get(key)}
        row = {'id': item.get('id', item['src']), 'src': item['src'], 'type': item['type']}
        sizes = {}
        reason = None
        for relative in sorted(dependencies):
            try:
                sizes[relative] = source_path(root, relative).stat().st_size
            except FileNotFoundError:
                reason = f'Missing dependency: {relative}'
                break
        if any(PurePosixPath(path).parts[0].lower() == 'lage_files' for path in dependencies):
            reason = 'Held locally in lage_files; excluded from Pages'
        elif any(size > MAX_FILE_BYTES for size in sizes.values()):
            reason = 'A dependency exceeds GitHub\'s 100 MiB file limit'
        if reason:
            excluded.append({**row, 'reason': reason})
        else:
            candidates.append((sum(sizes.values()), index, sizes, row))
    selected = set()
    included = []
    used = sum(files.values())
    for cost, index, sizes, row in sorted(candidates, key=lambda candidate: (candidate[0], candidate[1])):
        additional = sum(size for path, size in sizes.items() if path not in files)
        if used + additional <= budget - reserve:
            selected.add(index)
            included.append({**row, 'packageBytes': cost, 'addedBytes': additional})
            files.update(sizes)
            used += additional
        else:
            excluded.append({**row, 'packageBytes': cost, 'reason': 'Complete media package does not fit the remaining budget'})
    chosen = [item for index, item in enumerate(items) if index in selected]
    public_library = {**library, 'items': chosen}
    report = {'generatedAt': datetime.now(timezone.utc).isoformat(timespec='seconds'),
              'budgetBytes': budget, 'metadataReserveBytes': reserve, 'maxFileBytes': MAX_FILE_BYTES,
              'selection': 'Smallest complete media packages first; source catalog order retained',
              'sourceCounts': counts(items), 'includedCounts': counts(chosen),
              'excludedCounts': counts([item for index, item in enumerate(items) if index not in selected]),
              'excludedReasons': dict(Counter(row['reason'] for row in excluded)),
              'copiedBytes': used, 'files': [{'path': path, 'bytes': size} for path, size in sorted(files.items())],
              'included': included, 'excluded': excluded}
    plan = {'root': root, 'files': files, 'library': public_library, 'report': report}
    outputs = generated_files(plan)
    if report['totalBytes'] > budget:
        raise ValueError('Generated metadata exceeds the reserved budget; increase --reserve-bytes')
    if any(len(data) > MAX_FILE_BYTES for data in outputs.values()):
        raise ValueError('Generated file exceeds GitHub\'s 100 MiB file limit')
    return plan


def validate_output(root, output):
    root = Path(root).resolve()
    candidate = Path(output)
    if not candidate.is_absolute():
        candidate = root / candidate
    destination = candidate.resolve()
    if destination == root or not destination.is_relative_to(root) or '.git' in [p.lower() for p in destination.relative_to(root).parts]:
        raise ValueError('Output must be a new directory inside the repository, outside .git')
    current = candidate
    while current != root and current != current.parent:
        if current.is_symlink():
            raise ValueError('Output cannot pass through a symbolic link')
        current = current.parent
    if candidate.exists():
        raise ValueError('Output already exists; choose a new directory')
    relative = destination.relative_to(root).as_posix() + '/.pages-export'
    result = subprocess.run(['git', 'check-ignore', '--no-index', '-q', '--', relative], cwd=root,
                            capture_output=True)
    if result.returncode != 0:
        raise ValueError('Output must be ignored by Git; use qa-output/pages or add an ignore rule first')
    return destination


def file_digest(path):
    digest = hashlib.sha256()
    with path.open('rb') as stream:
        for chunk in iter(lambda: stream.read(4 * 1024 * 1024), b''):
            digest.update(chunk)
    return digest.digest()


def export_plan(plan, output):
    destination = validate_output(plan['root'], output)
    destination.mkdir(parents=True, exist_ok=False)
    for relative, expected_size in plan['files'].items():
        source = source_path(plan['root'], relative)
        if source.stat().st_size != expected_size:
            raise ValueError(f'Source changed since planning: {relative}')
        target = destination / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, target)
        if target.stat().st_size != expected_size or file_digest(target) != file_digest(source):
            raise ValueError(f'Copy verification failed: {relative}')
    for relative, data in generated_files(plan).items():
        target = destination / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
    actual = sum(path.stat().st_size for path in destination.rglob('*') if path.is_file())
    if actual != plan['report']['totalBytes'] or actual > plan['report']['budgetBytes']:
        raise ValueError('Export size failed the final budget check')
    for item in plan['library']['items']:
        for key in ('src', 'thumbnail', 'playbackSrc'):
            if item.get(key):
                source_path(destination, item[key])
    return destination


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--apply', action='store_true', help='Copy the selected snapshot; default only previews')
    parser.add_argument('--output', type=Path, default=Path('qa-output/pages'))
    parser.add_argument('--budget-bytes', type=int, default=DEFAULT_BUDGET)
    parser.add_argument('--reserve-bytes', type=int, default=DEFAULT_RESERVE)
    args = parser.parse_args(argv)
    plan = make_plan(ROOT, args.budget_bytes, args.reserve_bytes)
    report = plan['report']
    print(json.dumps({key: report[key] for key in ('includedCounts', 'excludedCounts', 'totalBytes', 'budgetBytes', 'excludedReasons')}, indent=2))
    if args.apply:
        destination = export_plan(plan, args.output)
        print(f'Export verified: {destination}')
        print('Original media and the working catalog are unchanged. No commit or push was made.')
    else:
        print('Preview only. Use --apply to export to a new ignored directory.')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
